### ISSUE TITLE
Version Info

### ISSUE THREAD

**Issue by hl2guide** [ncosgray/cuppa_mobile#108]
**The problem:**

Currently there is no in app indiction of what version is installed.

**Proposed solution:**

Show the version in the settings tab or in an **About** section.

**Comment by ncosgray** [comment]
Hello! The version number (and build number) should appear at the top of the About page, which is accessible via the "?" button on the Preferences page. Are you able to see this info?

![version](https://github.com/ncosgray/cuppa_mobile/assets/13181064/5712ad76-2480-4bc5-a4ed-ed853010254b)

**Comment by hl2guide** [comment]
thanks found that now 😳
