### ISSUE TITLE
Bug report: German Transaltion

### ISSUE THREAD

**Issue by LopeKinz** [ncosgray/cuppa_mobile#111]
As a fellow German the translation is very bad.
The words are Translated right but not every word needs to be in german. maybe get the newest transaltions from weblate

**Comment by ncosgray** [comment]
@LopeKinz -- thanks for the feedback! I'm sorry the quality of the German translation isn't better. Translations are contributed by users, so they're only as good as what's entered into Weblate. But input is definitely always appreciated and anyone with a Weblate login is able to edit strings and make corrections.

If you have the time, would you like to review the German translations and make improvements where needed? Here's a link: https://hosted.weblate.org/projects/cuppa/cuppa-mobile-app/de/

**Comment by LopeKinz** [comment]
> @LopeKinz -- thanks for the feedback! I'm sorry the quality of the German translation isn't better. Translations are contributed by users, so they're only as good as what's entered into Weblate. But input is definitely always appreciated and anyone with a Weblate login is able to edit strings and make corrections.
> 
> 
> 
> If you have the time, would you like to review the German translations and make improvements where needed? Here's a link: https://hosted.weblate.org/projects/cuppa/cuppa-mobile-app/de/

I already contributed to the German translation. Its way better now.
