### ISSUE TITLE
Feature request: Superfluous Statistics

### ISSUE THREAD

**Issue by pwd-github** [ncosgray/cuppa_mobile#120]
**The problem:** Display some totally unnecessary stats. 

**Proposed solution:** User has had XX Cups of tea in YY days. Consisting of ZZ% AA,  BB% CC, etc

You could even display it as a pie chart and use a cup of tea as the pie.

**Comment by ncosgray** [comment]
This is totally superfluous, and I totally love it.

**Comment by pwd-github** [comment]
😍
