### ISSUE TITLE
Feature request: Add a backup/restore method

### ISSUE THREAD

**Issue by serrq** [ncosgray/cuppa_mobile#128]
I added a lot of teas, so when I will change my device I would like to move my current teas in the new device.

**Comment by ncosgray** [comment]
Thank you for the suggestion. This was already on my roadmap but you've encouraged me to fast-track it! Export/import functionality will be included in the next Cuppa release. The goal is to have a convenient way to move or copy all settings and usage stats from one device onto another. Cuppa's export files use a simple JSON format that's easy to edit manually, too, if you wanted. Hope it proves helpful.
