### ISSUE TITLE
Feature request: Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [ncosgray/cuppa_mobile#130]
Please add direct cryptocurrency addresses within the app. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, DASH, EPIC, FTM, XRP, XDC, ADA, XLM, XMR addresses available for donations (addresses have to be copyable).

Here an integration example made by other developers.

![1000092943](https://github.com/AdamGuidarini/MediTrak/assets/113377431/528e3065-97e2-4851-a590-ecaece5e2727)

**Comment by ncosgray** [comment]
It's a bit hard to add donate links directly to apps without running afoul of app store rules. But, I've added my ETH address to [Support the Project](https://github.com/ncosgray/cuppa_mobile?tab=readme-ov-file#support-the-project), which is linked from the About page in today's [Cuppa 2.6.0](https://github.com/ncosgray/cuppa_mobile/releases/tag/2.6.0) release. I hope this makes it a bit easier to donate.
