### ISSUE TITLE
Feature request: Feature request:  teas vertically

### ISSUE THREAD

**Issue by serrq** [ncosgray/cuppa_mobile#132]
I believe that vertically be more efficient.

![1000102161](https://github.com/ncosgray/cuppa_mobile/assets/113377431/3c9bcb09-550a-4869-98ff-e0ad8228857c)

**Comment by ncosgray** [comment]
What a great suggestion! Vertical stacking allows showing at least twice the number of buttons on the screen. I've added an option to today's [2.6.0](https://github.com/ncosgray/cuppa_mobile/releases/tag/2.6.0) release that arranges tea buttons vertically in rows of 3 buttons. I think it works nicely, and I hope you agree.
