### ISSUE TITLE
Community discussion group

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#14]
- I made a discussion group on telegram, where users can discuss the app in real time: https://t.me/CuppaMobile
- Telegram is usually used for groups like this.
- If you dislike this decision, i can delete the group. 
- if you @ncosgray  join it, i will make you an Owner/admin of it.

**Comment by ncosgray** [comment]
Thank you! Good idea. I'll add a link to the Readme, too.
