### ISSUE TITLE
Notifications have stopped working

### ISSUE THREAD

**Issue by dknestaut** [ncosgray/cuppa_mobile#146]
**Steps to reproduce:**
1) Select any tea timer.
2) Wait for timer to count down to zero.

**Expected behavior:** What did you expect to happen when performing these steps?

I expect, upon reaching zero, that the app would make the clinking sound it normally makes, it will cause my phone to vibrate, and it will push a notification to both my phone's notification shade as well as my watch. 

**Observed behavior:** What actually happened and why is it a problem? If applicable, consider adding screenshots to help explain.

Nothing happened. Yesterday, when I made my evening cup of tea, it worked as expected. Today, when I made my morning cup, and again when I made my evening cup, it counted down to zero, but no notifications were served. Neither visual, audio, nor hepatic notifications were served.

**Device information:** Include your device operating system and version.

I'm currently using Android 14 on a Pixel Six. I am receiving notifications from other apps. I checked to make sure the notifications were not muted in the app. I made sure notifications were enabled in the system settings. I deleted the cache from the app, opened it again, granted it notification permissions again. No dice. I deleted the app, rebooted the phone, and reinstalled the app. Opened it again, granted it notification permissions once again. None of these efforts restored notifications.

This app was automatically installed on my Pixel tablet when I set it up, but I'd never used it on the tablet before. I opened it up on the tablet and found that the app is having the same lack of notifications on the Pixel tablet, which is also running Android 14.

**Comment by ncosgray** [comment]
Oh no! Thank you so much for reporting the problem. I've been able to reproduce this bug on my Pixel, and I think I have a fix for it. Look for version 2.7.1 shortly...

**Comment by ncosgray** [comment]
Version 2.7.1 has resolved the notifications bug on my Pixel running Android 14. Sorry about this—I will be careful to test on an actual device instead of just an emulator, going forward.

Please let me know if 2.7.1 doesn’t work for you.
