### ISSUE TITLE
Feature request: Change/disable sound effect

### ISSUE THREAD

**Issue by agwilt** [ncosgray/cuppa_mobile#158]
**The problem:** Personally I'm not a huge fan of the "teacup being put down" sound.

**Proposed solution:** Implement a radio button to change to vibration only, or (even better) an option to set a customised sound effect.

**Comment by ncosgray** [comment]
Hello! Thanks for using Cuppa, and thanks for the feedback!

One thing you could try is the “Start timers in silent mode” option in Cuppa Settings.

Aside from “silent mode”, Cuppa cedes most aspects of notification settings to your device’s operating system, which is best practice for apps on both platforms. iOS and Android each let you configure how Cuppa’s alerts act and sound via your App Notifications system settings. This is why Cuppa itself doesn’t have more granular alert settings—your device OS handles that. For example, if you don’t want Cuppa alerts to make an audible noise, you’d set that in your system settings. Android even lets you choose your own notification sound.

Cuppa includes a convenient shortcut to the system-level notification settings. On the Settings screen, tap “Open your device’s system settings to configure notifications for Cuppa.” You’ll see many settings there.

One final note: If you’re using Android, make sure to tap the “Timer notifications” channel name to get into the finest level of settings—this is where you change the notification sound, for example. It is very deeply buried in the Android OS settings, so I suspect a lot of people are unaware of just how much control you have over app notifications! :)

Please give it a try. I hope this info helps you find the best combination of settings that works for how you use the app.

**Comment by agwilt** [comment]
Mea culpa, I obviously didn't check the settings well enough. That does exactly what I want! And you just taught me something new about Android settings too :)

Thanks for helping me out and for making such a great app!
