### ISSUE TITLE
Weblate translating issue

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#16]
Some content isn't translatable currently, as it says it's in maintenance mode.

![slika](https://user-images.githubusercontent.com/50620416/124203235-8ab96c00-dadc-11eb-832a-2f723e29a998.png)

**Comment by ncosgray** [comment]
Thank you. It's unlocked now. I am still learning how Weblate integrates with GitHub! It's quite complex. Very likely there will be more hiccups... sorry in advance. :)
