### ISSUE TITLE
There are teas that brew less than one minute

### ISSUE THREAD

**Issue by benelot** [ncosgray/cuppa_mobile#19]
Hello! I just wanted to use your app to brew my green tea, but realized you can not configure teas brewing 45 seconds. What a shame! For loose leaf tea such short times are very common.

**Comment by ncosgray** [comment]
Good point! This will be fixed in the next release. (See https://github.com/ncosgray/cuppa_mobile/commit/14e6a6e49ed2a08676b9fa67703f74cf4908f0c2)
