### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by brylie** [ncosgray/cuppa_mobile#2]
Please consider adding an open-source license for this project.

https://choosealicense.com

**Comment by brylie** [comment]
I do see the license comments in the .dart files. Adding a LICENSE file to the repository root would make it a bit easier to figure out the project license.

**Comment by ncosgray** [comment]
Thank you for the suggestion. I've added a LICENSE.txt file.

https://github.com/ncosgray/cuppa_mobile/commit/6caca14f91145a786d70355531968b2be4c8527d
