### ISSUE TITLE
New feature: Countdown notification

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#25]
When the app is minimized, there is no notification indicator while the app is counting down so you can see how much time is left.

Please add a notification countdown timer, when the app is minimized. Similar to the stock android countdown timer when it is counting.

Example with the Android system countdown timer:
![signal-2021-09-08-124749_001](https://user-images.githubusercontent.com/50620416/132496533-9ab4ce42-2228-419e-ba90-62155e0c9342.jpeg)

EDIT: added photo and fixed text.

**Comment by mondlicht-und-sterne** [comment]
> When the app is minimized, there is no indicator of the fact that the app is counting down and what that time is.
> 
> Please add a notification countdown timer, when the app is minimized. Similar to the stock android countdown timer when it is counting.

So a notification comes to me.
Maybe you mean you could optionally set a sound, a ringtone, whatever, to be heard.

**Comment by aha999** [comment]
@mondlicht-und-sterne i'm talking about, if you start a timer, and then minimize the app... Will there be a notification with the countdown information ? Not here... Notification when the timer ends yes, but not while it's counting down, so you don't have to open the app to see how much time is left.

**Comment by ncosgray** [comment]
Closing because this functionality isn't supported by iOS. It could be added for Android, but I want there to be feature parity between versions of Cuppa for each mobile platform.
