### ISSUE TITLE
Donation platforms

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#28]
Is your feature request related to a problem? Please describe.
Currently there's no donating information, if users want to show appreciation like that.

Describe the solution you'd like
Add a Donations section to the readme and some buttons below as to where donate.

Describe alternatives you've considered
If you comment the information of the donation methods you use and addresses, i will do it for you and make a pull request, did this a couple of times.

I saw a lot of open-source projects use LiberaPay or other in the list: 
- [LiberaPay](https://liberapay.com/) -- [example](https://liberapay.com/k9mail/donate)
- [PayPal](https://www.paypal.com/)
- [Github Sponsors](https://github.com/sponsors)
- [Ko-fi](https://ko-fi.com/)
- [OpenCollective](https://opencollective.com/) -- [example](https://opencollective.com/darkreader#sponsor)
- [Flattr](https://flattr.com/)
- [BountySource](https://www.bountysource.com)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) 
Some [donate buttons](https://github.com/aha999/DonateButtons)

**Comment by ncosgray** [comment]
Thanks for the suggestion. Right now I only use PayPal for donations, so I added that via a FUNDING file (https://github.com/ncosgray/cuppa_mobile/commit/299495cc5c79c789a833cb174401442c2ea1547f). I'll reopen this issue and let you know if I set up other donation methods and need help with sponsor buttons.
