### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#3]
It would be really nice if you could release the app on [F-Droid](https://www.f-droid.org/), where most of the open source android apps are.
It could get community more involved as your app would be findable there.

**Comment by ncosgray** [comment]
Thank you. I am planning to release Cuppa via F-Droid starting with the next version!

**Comment by ncosgray** [comment]
Submitted: https://gitlab.com/fdroid/rfp/-/issues/1725

**Comment by ncosgray** [comment]
Cuppa is available on F-Droid now!

https://f-droid.org/en/packages/com.nathanatos.Cuppa/

😃

**Comment by aha999** [comment]
Awesome! i wish you many downloads! :D
