### ISSUE TITLE
Favourite teas feature

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#33]
Add an option to favourite teas, so these would display at the top of the list.

This would be useful when users will add many teas to their tea list and would like their favourite ones at the top.

As @mondlicht-und-sterne mentioned in issue #20 :

> When more (or many) teas have been added to Cuppa, it could also be possible to display teas as favourites, i.e. you could then select and deselect the favourites yourself.

**Comment by ncosgray** [comment]
Reordering teas in Preferences goes some way toward achieving this, but a future version will include the ability to mark/select which teas are favorites.
