### ISSUE TITLE
More animations

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#36]
Add an option where we can change animation types.

Ideas:
- Hourglass, where speed of animation is set by time from start to finish
Video example: [link](https://youtu.be/1Q0dgNO1-Bs)

Also, found some great animations that could be used: [link](https://medialoot.com/preview/frame/animated-svg-preloaders.html), like if you're a chemist, you may like a beaker, if you're a mechanic, you may like a gear etc... Hourglass on page 12

**Comment by ncosgray** [comment]
This is not something I'm personally interested in -- the Cuppa Mobile app and macOS apps are companion apps sharing the same teacup graphics and tea-darkening animation, and I prefer to keep it that way. I also do not have plans to add other animations to the macOS app. I have to focus my time and energy elsewhere. Sorry about that!
