### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ncosgray/cuppa_mobile#38]
1. create categories
2. being able to classify teas into categories
This has the advantage that you do not have to enter the categories each time.

Examples::

### Black Teas
Black Tea
Assam
Ceylon
Earl Grey

### White Teas
White Tea
Pai Mu Tan
Xin Zhen

**Comment by ncosgray** [comment]
The design concept of Cuppa is to be a simple tea timer with only the minimum functionality needed to track your tea steeping preferences and easily initiate a tea timer. 

Can you share your reasoning / use case for adding tea categories to the app? How would this be useful? How would it fit into the minimalist concept of the Cuppa app? I'm not totally discounting this idea, but I don't immediately see why someone would want a tea category in a tea timer app for anything other than informational purposes. Unlike tea steep time and temperature, it is not necessary to know the tea type when brewing one's tea.

Also, what would this look like in the UI?

**Comment by mondlicht-und-sterne** [comment]
you always talk about the minimum, 1 tea is enough. that is the minimum.

**Comment by ncosgray** [comment]
Haha, fair enough! :)

**Comment by ncosgray** [comment]
I would like to suggest using tea colors to categorize your teas. For example, I set all my black teas to the gray color, and my green teas to the green color.

The next version of Cuppa will add more color choices too, so that might help.
