### ISSUE TITLE
Feature request: Change images from .png to vector 

### ISSUE THREAD

**Issue by Throlo** [ncosgray/cuppa_mobile#40]
As the title says, changing to vector images will look better.

**Comment by ncosgray** [comment]
I really like this idea a lot!

Unfortunately, I don't have the technical or artistic skills to recreate the Cuppa graphics as vector art. I've labeled this "help wanted" in case you or anyone else would like to contribute new vector artwork to the project.

I should also note that [Flutter](https://flutter.dev) doesn't natively support vector graphics, although there is an [ongoing discussion](https://github.com/flutter/flutter/issues/1831) about that. In the meantime the [flutter_svg](https://pub.dev/packages/flutter_svg) plugin does offer limited SVG support, so converting to vectors in the app *should* be doable.

**Comment by Throlo** [comment]
I have some pratice and i can draw simple things in vector format, if you need something just say me what.
