### ISSUE TITLE
Measurement system toggle ?

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#43]
When installing an app, temperatures are automatically displayed in an Imperial measurement system, which is a problem if you use metric system like most of the countries and don't know to convert the temperatures.

Could there be a settings toggle, Measurements: Metric/Imperial ? 

This way it would convert temperatures, change  measurement from Fahrenheit to Celsius or vice-versa, and we could also avoid displaying of 2 measurement systems in the temperature selection.

Maybe it could select that feature automatically based on a local system settings (if that's possible), or maybe there could be an introduction screen when first-ever running the app with the option to set this.

**Comment by lightonflux** [comment]
In terms of first time experience it would be great if Cuppa followed the locale system setting.
