### ISSUE TITLE
Feature request: Option to remove all teas

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#47]
Maybe some people only use the app for one or two teas, or maybe some just want to delete all teas to set them again from the start.

Add an option to remove all teas from the list.

If all teas are removed, there should be a message on the main screen, where the tea buttons normally are, message saying "add teas in settings" or something like that.

**Comment by ncosgray** [comment]
I've implemented a "Remove All Teas" button in a test build of Cuppa, and it's handy for my own personal regression testing, but I'm reconsidering whether to actually add it to the app for everyone. For one thing, it's almost as easy to just swipe to delete any teas you don't want.

The use case for a button to do this for you seems exceedingly limited. I would expect most users to press a "Remove All Teas" button at most one time, when they are configuring their tea preferences immediately after installing Cuppa for the first time.

Can you think of any other scenarios?

If not, I'm wondering if what's actually needed is an onboarding wizard, where new users of Cuppa would be stepped through a couple of screens introducing the app's functionality and then prompting them to add their favorite tea(s). In this way, they would have the right tea buttons from the first time they ever open the app and there'd be no need to clear out the existing/default tea preferences.

**Comment by aha999** [comment]
I agree, since swiping is the most obvious method of deleting teas, that for most users it would be an unnecessary function to have all teas deleted at once, but in case this function being implemented, a prompt "are you sure you want to remove all teas" would be handy in case of accidental clicks.

As a separate topic, an onboarding wizard would be great. I will create a new issue if there isn't one already.
