### ISSUE TITLE
Custom tea timers

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#5]
Allow the option to create custom tea timers with custom names, times, temperatures etc.

Also add the option to delete the timers.

**Comment by ncosgray** [comment]
[Version 1.4](https://github.com/ncosgray/cuppa_mobile/releases/tag/1.4) added a Preferences screen where users can set up their teas and enter custom names, times, and icon colors.

**Comment by aha999** [comment]
Issue was, that user would get the option to:
- Create new timers for other teas
- Delete timers
- Set temperature (next to time)

**Comment by ncosgray** [comment]
My apologies, I misunderstood this to be a request to customize teas with different names and times. I see now that you were asking to add more than 3 teas. In any case, this should be covered by the "more teas" milestone.
