### ISSUE TITLE
Change tea colour in image over time

### ISSUE THREAD

**Issue by lightonflux** [ncosgray/cuppa_mobile#51]
Nice to have feature: change the colour of the tea in the image with the cup while the countdown is running. 

This might be possible by using the flutter svg plugin andupdating the colour within the svg over time.

**Comment by ncosgray** [comment]
Hello! Thanks so much for the suggestion. Hope you are enjoying the app. :)

This is actually already implemented -- see https://github.com/ncosgray/cuppa_mobile/commit/34698d0d928b617eb2b9150f667eb0ffd5778588. The effect is subtle, but when you press a tea button to start a timer, the tea in the cup immediately lightens to a pale brown color, and then darkens very gradually over time.
