### ISSUE TITLE
Temperatures in Celcius

### ISSUE THREAD

**Issue by ortolot** [ncosgray/cuppa_mobile#53]
Hello,

Thank you for Cuppa, very useful!
Could you implement an option to use temperatures in Celcius? In regions using the metric system, Fahrenheit degrees are just meaningless. 🙂

**Comment by ncosgray** [comment]
Hello! I'm so glad you're finding Cuppa useful!

I have good news -- this will be addressed in the next version of Cuppa, which I expect to release within the next week or so. See issue #43. Basically, Cuppa will default to Celsius for everyone except for those of us in backwards USA. There will also be a temperature units toggle in Preferences.
