### ISSUE TITLE
Landing page/website improvement

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#55]
In my opinion, Github Readme currently looks better than your website for the app sharing.

I hope you can improve your website in a way, that the entire page (for example) or a selected tab is being used, whereas currently a lot of the left side of the screen is used for other info not related to the app. It looks sort of like a blog.

![image](https://user-images.githubusercontent.com/50620416/140652249-41f53731-25a6-4e53-b05d-0ac505d1e808.png)

Examples of app landing pages: https://designshack.net/articles/inspiration/best-app-landing-page-templates/

**Comment by ncosgray** [comment]
Thanks for the feedback. The website is a work in progress. I am testing WordPress plugins that interface with GitHub -- the idea is the Cuppa-related content on my site will all be loaded from the GitHub repos, which should help.

**Comment by ncosgray** [comment]
The [Nathanatos Software website](https://www.nathanatos.com) is now just a launch page that directs users to the apps' GitHub sites.

**Comment by aha999** [comment]
It would make sense to add 2 download buttons to your website, Google play and Fdroid
