### ISSUE TITLE
Temperature info

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#6]
Tea steeping water temperature is important. 
Please add Temperature presets to the existing teas.

probably:

- Black Tea: 100°C
- Green Tea: 80°C
- Herbal Tea: 100°C

**Comment by ncosgray** [comment]
This is an interesting idea. I may consider adding temperature info as part of a future redesign, but for now it is not in the cards, as it doesn't really fit with the vision and current aesthetic of the app. By way of explanation, Cuppa is meant to be nothing more than an easy and simple tea timer that includes nothing more than the essentials needed to keep track of when your tea is finished brewing.

**Comment by aha999** [comment]
100°C for green tea or white tea with the same time will ruin the taste.
80°C for black or herbal tea - never heard of, because it is  always 100°C.
and other teas also require different temperatures....

Tea time **needs** a combination of tea temperature in tea preparation/timing. Also, basically all such apps have it.

**Comment by ncosgray** [comment]
> 100°C for green tea or white tea with the same time will ruin the taste.
> 80°C for black or herbal tea - never heard of, because it is always 100°C.
> and other teas also require different temperatures....
> 
> Tea time **needs** a combination of tea temperature in tea preparation/timing. Also, basically all such apps have it.

I completely agree that temperature is crucial for brewing tasty teas! It's why I invested in a tea kettle with adjustable temp. :)

I am just unsure how to integrate temperature into the app in a way that is both useful and fits with the aesthetic. The only thing I can think of is to add it to the tea buttons on the main timer page, but I that would significantly increase the size of the buttons and would make the interface look too busy (in my opinion). But I'm certainly open to your suggestions and ideas.

Exactly how do you envision temperature being added to the app? Where would it be added and how would it fit into the design?

**Comment by aha999** [comment]
this was my [favourite app](http://mightytimer.com/) because the design of it, when i used an iphone and it includes a temperature (look at the screenshots).

I think the temperature info could be added here:

![slika](https://user-images.githubusercontent.com/50620416/125931388-c2eed8bf-ffde-4b5d-ab61-41feefe82773.png)

**Comment by ncosgray** [comment]
Thanks! My concern was really more about how to add the temperature info to the main app screen. I've been able to accomplish that in a way I'm fairly happy with:

![image](https://user-images.githubusercontent.com/13181064/128646821-e0568d5f-bda6-4f34-8c22-8ba7cdb0686a.png)

Brew temperature (C or F), and whether or not to display it on the tea timer buttons, will be a configurable option in the next release.

**Comment by aha999** [comment]
That's great! Considering the fact that almost all of the world countries use Metric units of measurements, would Celsius be displayed by default, and would there be a switch in the settings ?

**Comment by ncosgray** [comment]
You'll be able to select a Celsius or Fahrenheit temperature, yes. :)

**Comment by ncosgray** [comment]
Included in [version 1.4.4](https://github.com/ncosgray/cuppa_mobile/releases/tag/1.4.4) which is available on the Google and Apple stores now. F-Droid should pick up this release within the next few days.
