### ISSUE TITLE
Bug report: Android notification has no timestamp

### ISSUE THREAD

**Issue by ncosgray** [ncosgray/cuppa_mobile#67]
**Steps to reproduce:** Start a timer and wait for a Brewing Complete notification.

**Expected behavior:** Brewing Complete notification should include a timestamp telling the user when the timer finished, e.g. "now" or "5 min ago".

**Observed behavior:** The notification does not show a timestamp at all.

**Device information:** Android.

**Comment by aha999** [comment]
it would make sense to combine this with #25
