### ISSUE TITLE
Different sound notifications

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#7]
Currently there is no setting to choose a notification sound when the timer is done.

Add the setting to choose between different sounds when the time runs out.

**Comment by ncosgray** [comment]
Android includes this functionality at the OS level! :) Please check your device settings. For example, on stock Android 11, go to App Info for Cuppa, tap Notifications, then Timer Notifications, Advanced, Sound.

iOS does not currently allow changing notification sounds per app, but perhaps Apple will add that someday.

**Comment by aha999** [comment]
i know this, but it would certianly be nice, more convenient and tailored for Cuppa, if it offered more zen-sound options inside the app, instead of users having to resort to Android system settings. I think that people generally will not change app-specific notificaitons outside of the app...

**Comment by hl2guide** [comment]
@ncosgray please recosider allowing us to set a custom sound for when the timer elapses. 🙂

**Comment by ncosgray** [comment]
Hello @hl2guide!

If you're using Android, you can supply your own notification sound via your device settings, as I described in the comment I posted on May 21, 2021.

While it would be nice if Cuppa could present a list of app-specific notification sound options for users to choose from, Android does not allow apps to programatically change their own notification sounds. You will notice in Google's own apps such as Messages and Gmail, as well as in third-party apps like Signal and Instagram, that you cannot change the notification sound in the app. Instead, you must use the Android system settings for app notifications. If you're curious to learn more about about this you can read the Android Developer docs: https://developer.android.com/develop/ui/views/notifications/channels

**Comment by hl2guide** [comment]
> Hello @hl2guide!
> 
> If you're using Android, you can supply your own notification sound via your device settings, as I described in the comment I posted on May 21, 2021.
> 
> While it would be nice if Cuppa could present a list of app-specific notification sound options for users to choose from, Android does not allow apps to programatically change their own notification sounds. You will notice in Google's own apps such as Messages and Gmail, as well as in third-party apps like Signal and Instagram, that you cannot change the notification sound in the app. Instead, you must use the Android system settings for app notifications. If you're curious to learn more about about this you can read the Android Developer docs: https://developer.android.com/develop/ui/views/notifications/channels

For me I don't get my default notification sound, I get the sound of a spoon going around the top a cup.

**Comment by ncosgray** [comment]
> For me I don't get my default notification sound, I get the sound of a spoon going around the top a cup.

Have you changed the setting in your system preferences for Cuppa Notifications? You can use the shortcut on the Preferences screen ("Open your device's system settings to configure notifications for Cuppa"). Then, you have to tap Timer Notifications > Sound, and choose your default notification sound.

**Comment by hl2guide** [comment]
Tried finding that, no luck.

![1](https://github.com/ncosgray/cuppa_mobile/assets/17044982/7268961f-ee86-4303-8fdc-66d3c8e076bf)

No ability to set sound file.

I'll just use it as is.

**Comment by ncosgray** [comment]
@hl2guide did you tap on Notification Categories?Timer Notifications settings may be in there.

It's very difficult to give precise instructions because each version of Android is different and of course each phone manufacturer adds their own modifications. But if that doesn't work, please let me know what kind of device and Android version you have and I'll help you research this.

**Comment by aha999** [comment]
> Tried finding that, no luck.
> 
> ![1](https://github.com/ncosgray/cuppa_mobile/assets/17044982/7268961f-ee86-4303-8fdc-66d3c8e076bf)
> 
> No ability to set sound file.
> 
> I'll just use it as is.

it is in my android 11 (zenfone 6)

![Screenshot_20230522-131332826 (1).jpg](https://github.com/ncosgray/cuppa_mobile/assets/50620416/0df64740-7375-48b5-ad2b-f2d5efb99034)

**Comment by aha999** [comment]
@hl2guide maybe you have those settings somewhere separately or in not obvious places. I have the setting on my android 11 (zenfone 6).
