### ISSUE TITLE
Button Labels Fixup

### ISSUE THREAD

**Issue by hl2guide** [ncosgray/cuppa_mobile#85]
**Steps to reproduce:**
1) Open to main screen (first page)

**Expected behaviour:** What did you expect to happen when performing these steps?

Button labels fit on buttons.

**Observed behaviour:** What actually happened and why is it a problem? If applicable, consider adding screenshots to help explain.

Some button labels don't fit horizontally.

**Device information:** Include your device operating system and version.
Android 7.0 mobile phone.

_Screenshots:_

![Cuppa1](https://user-images.githubusercontent.com/17044982/190422114-aa747213-c002-4cd0-9fae-7d38575ea9d9.png)
![Cuppa2](https://user-images.githubusercontent.com/17044982/190422121-51887301-9db4-4c97-9941-108dcac45d91.png)

**Comment by ncosgray** [comment]
True, depending on the size of your screen, the names of your teas, and the orientation of your device (portrait or landscape) there may not always be sufficient space to render 100% of the first 3 tea buttons. You may need to scroll.

This is one of the main reasons why the tea button list is horizontally scrollable. Considering the infinite variety of phone sizes, tea names, OS font sizes, and other variables, it would be quite a challenge to ensure your teas always fit on the screen.

**Comment by ncosgray** [comment]
I wanted to close the loop on this a little bit better. The next version of Cuppa will clip the tea buttons at the edge of your phone's screen, rather than at the edge of the margin. I think this will make it more obvious that it's a scrolling list.

I hope that helps! :)
