### ISSUE TITLE
No sound upon notification

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#89]
**Steps to reproduce:**
1) Set a timer
2) Wait
3) Notification will produce no sound, except a vibration.

**Expected behavior:** 

When a timer is finished, there should be a sound notification, so we can know audibly that the tea is ready.

**Observed behavior:** 

When a timer is finished, there is no sound in a notification, even when the phone's volume settings are all set on highest setting.  The phone only vibrates.

This issue has been going on for a while and it prevents me from using the app efficiently.

**Device information:** 

Asus Zenfone 6, stock Android 11

**Comment by ncosgray** [comment]
Hello!

Do you recall which version this started happening on?

It seems you're getting an alert from the app, but it's just not audible? What troubleshooting steps have you tried?

I'd recommend first checking your system settings related to Cuppa notifications, and make sure you have allowed the app to produce an audible alert. You can tap the link at the bottom of the Cuppa Preferences screen to get there quickly. And from there, it is *very important* to tap "Timer notifications" to access all the available notification options. Sound should be set to "App provided sound" or some other sound of your choice.

You could also try uninstalling Cuppa and reinstalling -- this will completely reset the notification settings.

I hope that works. Let me know!

**Comment by aha999** [comment]
I just reinstalled Cuppa, and the audible notification (*clank* sound) is back. I've been having this issue for some versions now I believe, but it could've been my Android settings somehow.

**Comment by ncosgray** [comment]
When I changed from regular notifications to alarms, that may have caused the issue. Sorry! I'm glad it's working now. 👍🏻
