### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#9]
if this app is going to be actively developed, it would be great if there was a way for general public to contribute translations.

I can recommend [Weblate](https://weblate.org/), as the platform itself is open source (compared to others), can be self hostable, and for open source projects like yours, they host translations for free. Weblate automatically makes pull requests afaik and if you want you can have a widget shown on github, that displays how much percentage each applied language has translated.  It's much more simple for people to translate this way and it's free.

- [set up your libre project](https://hosted.weblate.org/hosting/) 

screenshot:
![slika](https://user-images.githubusercontent.com/50620416/119900111-57ffdf00-bf44-11eb-95e6-892f025a7627.png)

**Comment by ncosgray** [comment]
Thank you! Localization is near the top of my to-do list but I've been wondering about the best way to approach it. I was unaware of Weblate and it seems perfect for this project. I really appreciate the pointer.

**Comment by comradekingu** [comment]
I can help if you add https://hosted.weblate.org/user/kingu/#managed :)

**Comment by ncosgray** [comment]
@comradekingu Wonderful! I added Cuppa to Weblate today: https://hosted.weblate.org/projects/cuppa -- Check it out!
