### ISSUE TITLE
Feature request: Introduction wizard / tutorial

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#95]
**The problem:** Currently when a Cuppa app is installed, a user is expected to know the functions of the app, since there is no helper information.

**Proposed solution:** Implement an onboarding wizard or an introductionary helper / tutorial, that would tell the user of the main functions, where to find them or guide the user towards that functions by showing arrows. This issue can have more similar functions added to it.

**Comment by ncosgray** [comment]
Thank you so much for this input! In the next version, there will be an onboarding guide for new users that briefly explains how the app works. It will be shown only once **for brand-new installations of Cuppa** (if you already have the app installed, you won't see it!) but the tutorial will also be accessible from the About screen.

You can see what the new tutorial will look like and contribute translations of the text in Weblate: https://hosted.weblate.org/translate/cuppa/cuppa-mobile-app/en/?&offset=52
