### ISSUE TITLE
Bug report: Follow system says it's a black theme

### ISSUE THREAD

**Issue by aha999** [ncosgray/cuppa_mobile#98]
**Expected behavior:** What did you expect to happen when performing these steps?
In the theming options, the follow system is said to be black, while it should say Dark, as i have a dark system theme.

**Observed behavior:** What actually happened and why is it a problem? If applicable, consider adding screenshots to help explain.
It's not accurate, as Black or Dark system themes are different

**Device information:** Include your device operating system and version.
Asus Zenfone 6, Android 11
![Screenshot_20230201-034612887 (1).jpg](https://user-images.githubusercontent.com/50620416/215933520-bfe1f87c-c5d2-4f8a-a115-5165dd614c87.jpg)

**Comment by ncosgray** [comment]
Hello! In response to issue #93, I made the black theme distinct from the dark theme. This means there are by necessity five different theming options:

1. Follow system = Light theme when OS is set to bright, dark (grey) theme when OS is set to dark
2. Light = Always light theme regardless of OS settings
3. Dark = Always dark (grey) theme regardless of OS settings
4. Black = Always pure black theme regardless of OS settings
5. Follow system (Black) = Light theme when OS is set to bright, pure black theme when OS is set to dark

So to clarify, are you asking that option 1 be relabeled as "Follow system (Dark)"?

**Comment by ncosgray** [comment]
@aha999, did you have any additional thoughts about this? I haven't received any feedback from other people about the wording in the theme options menu.

**Comment by aha999** [comment]
@ncosgray you mean, you have this already in a separate issue?

**Comment by ncosgray** [comment]
> @ncosgray you mean, you have this already in a separate issue?

I mean, I would like to close the issue. :) I don't think this is a problem since there actually are two different dark themes (dark grey and pure black), so by necessity there have to be two options for Follow System too.

**Comment by ncosgray** [comment]
Closing this issue as I don't plan to make any changes to the theme selection UI at this time.
